const data = [
  {
    id: 1,
    fname: "John",
    lname: "Doe",
    email: "doe@gmail.com",
    age: 35,
    contact: "09877665543",
    address: {
      country: "pakistan",
      city: "karachi",
    },
    activityType: "Bicycle",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    duration: 2,
    date: "2023-01-03",
  },
  {
    id: 2,
    fname: "Ali",
    lname: "Ahmed",
    age: 25,
    email: "ali@gmail.com",
    contact: "01234567889",
    address: {
      country: "Pakistan",
      city: "Sukkur",
    },
    activityType: "Swimming",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    duration: 3,
    date: "2023-02-17",
  },
  {
    id: 3,
    fname: "Jack",
    lname: "Black",
    age: 28,
    email: "jack@gmail.com",
    contact: "12345665543",
    address: {
      country: "Australia",
      city: "Sydney",
    },
    activityType: "Running",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    duration: 4,
    date: "2023-03-13",
  },
  {
    id: 4,
    fname: "Jane",
    lname: "Stock",
    age: 24,
    email: "Jane@gmail.com",
    contact: "09877665543",
    address: {
      country: "USA",
      city: "New York",
    },
    activityType: "Boxing",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    duration: 2,
    date: "2023-02-22",
  },
  {
    id: 5,
    fname: "Kumar",
    lname: "Gupta",
    age: 22,
    email: "gupta@gmail.com",
    contact: "09877665543",
    address: {
      country: "South Africa",
      city: "Capetown",
    },
    activityType: "Weight lifting",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
    duration: 3.5,
    date: "2023-04-10",
  },
];

export default data;
